version: '3.9'

volumes:
  grafana-storage:

networks:
  loki:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config:/etc/loki
    networks:
      loki:
        ipv4_address: 172.21.0.5
  
  grafana:
    image: grafana/grafana:10.4.4
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_SECURITY_ADMIN_USER=admin
#    entrypoint:
#      - sh
#      - -euc
#      - |
#        mkdir -p /etc/grafana/provisioning/datasources
#        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
#        apiVersion: 1
#        datasources:
#        - name: Loki
#          type: loki
#          access: proxy
#          orgId: 1
#          url: http://loki:3100
#          basicAuth: false
#          isDefault: true
#          version: 1
#          editable: false
#        EOF
#        /run.sh
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/config/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      loki:
        ipv4_address: 172.21.0.6
  
  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - /var/log:/var/log
      - ./promtail/config:/etc/promtail
    command: -config.file=/etc/promtail/local-config.yaml
    networks:
      loki:
        ipv4_address: 172.21.0.7
